### ISSUE TITLE
Route migration doesn't update hostname for 3.x destination clusters

### ISSUE THREAD

**Issue by sseago** [migtools/openshift-migration-plugin#23]
The Route restore plugin uses a 4.x-specific ConfigMap to locate the appropriate cluster hostname to update routes. If the destination cluster is 3.11 or older, the plugin doesn't replace the subdomain at all.

**Comment by jwmatthews** [comment]
I've done migrations of routes from 3.11 to 4.1 and haven't noticed an issue.

Is this a problem with clusters older than 3.11?  So 3.7, 3.9, and 3.10?

**Comment by jwmatthews** [comment]
Ah missread....
destination cluster is 3.11....

**Comment by sseago** [comment]
Yes this is specific to destination clusters, since the mechanism we're using to determine the domain name doesn't work for 3.11 or older. We keep migration from failing by checking for version and just not updating it for 3.x destinations, but the real fix is to figure out how to determine the domain name from a 3.x cluster. Worst-case scenario we create a custom ConfigMap and instruct customers that if they're migrating to 3.x they need to create this for routes to be updated. Better would be if something similar to the 4.x ConfigMap actually exists already.

**Comment by sseago** [comment]
Fix is here: https://github.com/fusor/openshift-velero-plugin/pull/5
and here: https://github.com/fusor/openshift-migration-plugin/pull/24

**Comment by sseago** [comment]
It turns out we don't have to mess with ConfigMaps at all. If the "openshift.io/host.generated" is "true", then we strip Spec.Host on restore and let the dest cluster figure it out.

**Comment by sseago** [comment]
Fixed, closing.
