### ISSUE TITLE
Merging migration-plugin and openshift-velero-plugin into single repository

### ISSUE THREAD

**Issue by Danil-Grigorev** [migtools/openshift-migration-plugin#38]
Currently there are two repos used in production migration-plugin deployment ([migration-plugin](https://github.com/fusor/openshift-migration-plugin), [velero-plugin](https://github.com/fusor/openshift-migration-plugin)). 

While working on improvements for both, resolving dependency issues is delaying development progress. So merging into single repo is necessary. Should be added support for plug-in functionality of the openshift-migration-plugin, for use-cases, when a backup/restore on a single cluster is required only.

From discussion with @sseago this could be a several-step approach:
1) Add an annotation (say `part-of=openshift-migration`), which will determine if the `migration-plugin` should be initiated.
1) Make sure the migration-controller does not initiate migration-specific tasks, when there is no need for backup/restore. Add conditionals and blocks where the handling is needed.
3) Testify and merge [velero-plugin](https://github.com/fusor/openshift-migration-plugin) into current repo.

**Comment by sseago** [comment]
The annotation is already added by the controller. We just need to check for it. Actually it's a label, added to the backup/restore CRs. "app.kubernetes.io/part-of=openshift-migration"
