### ISSUE TITLE
Allow for a user to skip the migration of builds

### ISSUE THREAD

**Issue by dymurray** [migtools/openshift-migration-plugin#55]
There has been a number of users with feedback given that they would prefer we do not replay the builds on the destination side. We should expose a configuration option which would allow a user to create migrations which will not include builds from the source cluster.

**Comment by sseago** [comment]
What's the use case for ever restoring builds? Some may fail anyway, and if they don't, they're creating new images that won't necessarily be the same as the images associated with these old builds on the src cluster.

**Comment by dymurray** [comment]
We have merged in a fix to never restore builds.
